language: python
dist: jammy
python:
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt -r requirements-test.txt
  - pip install .
script:
  - make test
  - ubuntu-bug-triage -h
