name: ubuntu-triage
summary: Recently updated Launchpad bugs for triage
description: |
    Get involved and help fix Ubuntu bugs! Obtain a list of bugs for an
    Ubuntu team or package that were created or updated yesterday.

    Users can further define the number of days to triage to increase
    the number of bugs found, the output type to allow machine readable
    output, or set the behavior to open the bugs in a browser and
    immediately begin bug triage.

version: git
version-script: git rev-parse --short HEAD
grade: stable
confinement: strict
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-triage:
        command: bin/ubuntu-triage
        plugs:
            - browser-support
            - desktop
            - network
            - network-bind

parts:
    ubuntu-triage:
        plugin: python
        source: https://github.com/powersj/ubuntu-triage
        source-type: git
        stage-packages:
            - libdb5.3
            - libffi-dev
            - libssl-dev
